# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "experimental"
  end

  config.vm.provision "file", source: "~/Workspace/Vagrant/setup/bashrc", destination: "/home/vagrant/.bashrc"
  config.vm.provision "file", source: "~/Workspace/Vagrant/setup/tmux.conf", destination:"/home/vagrant/.tmux.conf"
  config.vm.provision "file", source: "~/Workspace/Vagrant/setup/xterm-kitty", destination:"/home/vagrant/.terminfo/x/xterm-kitty"
end
